### ISSUE TITLE
Plugin not working on rabbitmq-server version 3.8.4-1

### ISSUE THREAD

**Issue by ravihara** [rabbitmq/rabbitmq-lvc-exchange#23]
Today, we have upgraded the rabbitmq-server and placed this plugin appropriately. We could see this plugin in the list of loaded plugins and also, our exchange was showing all fine except that, none of the published messages were getting into the queue.

Temporary resolution: We have downgraded the rabbitmq-server to 3.8.3-1 and things started working again. So, it looks likes, somewhere in the plugin internal logic it has become incompatible with 3.8.4-1 of rabbitmq-server.

**Comment by ravihara** [comment]
I guess, issue logged at wrong place. Sorry!

**Comment by michaelklishin** [comment]
@ravihara just so that our team and the readers can find it, would you mind linking to the correct place? What plugin are we talking about?

**Comment by lukebakken** [comment]
@ravihara you must download the plugin from this URL for 3.8 versions of RabbitMQ:

https://github.com/rabbitmq/rabbitmq-lvc-exchange/releases/tag/v3.8.0

Test process:

* Download, install and enable the plugin from the above url
* Start RabbitMQ
* Create an exchange with `x-lvc` type called `lvc`
* Create a queue, bind to the exchange using routing key `test-lvc`
* Publish a message to the `lvc` exchange using routing key `test-lvc`. The message shows up in the queue.
* Create a new queue, bind to the exchange using routing key `test-lvc`
* As expected, the same message is routed to the new queue

**Comment by ravihara** [comment]
Hi Sorry!! It's my bad.. I was raising the issue for https://github.com/rabbitmq/rabbitmq-delayed-message-exchange (delayed exchange plugin) but, wrongly landed at this repo by mistake.
