### ISSUE TITLE
Plugin does not start with {invalid_ez,einval} error

### ISSUE THREAD

**Issue by Baldro** [rabbitmq/rabbitmq-lvc-exchange#27]
I am trying to use lvc plugin latest version 3.8.0 on a rabbitmq in docker.

FROM rabbitmq:3-management
COPY ./rabbitmq_lvc_exchange-3.8.0.ez /plugins/rabbitmq_lvc_exchange-3.8.0.ez

The docker starts successfuly, but logs the below error for the lvc plugin:

`Problem reading some plugins: [{"/opt/rabbitmq/plugins/rabbitmq_lvc_exchange-3.8.0.ez",{invalid_ez,einval}}]`

**Comment by lukebakken** [comment]
Is this the _complete_ contents of your `Dockerfile`?

```
FROM rabbitmq:3-management
COPY ./rabbitmq_lvc_exchange-3.8.0.ez /plugins/rabbitmq_lvc_exchange-3.8.0.ez
```

Can you please describe exactly how you're downloading the plugin? This is to prevent me from doing something different. Thanks.

**Comment by Baldro** [comment]
Yes that is the content of the docker file.

I downloaded the plug-in from the last tagged version:

https://github.com/rabbitmq/rabbitmq-lvc-exchange/releases/tag/v3.8.0

**Comment by lukebakken** [comment]
Let me ask again ... can you please describe *exactly how* you're downloading the plugin? Are you using a browser, `curl`, etc? Tell me the exact method used and provide output. The reason I ask is that sometimes people use `curl` but forget to tell it to follow redirections, resulting in a bad file and the `{invalid_ez,einval}` error.

Compare your download with mine:

```
$ curl -LO https://github.com/rabbitmq/rabbitmq-lvc-exchange/releases/download/v3.8.0/rabbitmq_lvc_exchange-3.8.0.ez
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   652  100   652    0     0   1288      0 --:--:-- --:--:-- --:--:--  1288
100 11883  100 11883    0     0  11894      0 --:--:-- --:--:-- --:--:-- 32290
lbakken@shostakovich ~/Downloads
$ sha256sum rabbitmq_lvc_exchange-3.8.0.ez 
cff2e6406b17131571b6991d405e5ebb129420af7b7565cbe5667807ea3920c0  rabbitmq_lvc_exchange-3.8.0.ez
```

**Comment by lukebakken** [comment]
I'm assuming that your download method produced an invalid file. The above works fine using RabbitMQ `3.8.10` locally:

```
^C(23.2.2)lbakken@shostakovich ~/issues/rmq-generic-unix/rabbitmq_server-3.8.10
$ ./sbin/rabbitmq-plugins list rabbitmq_lvc_exchange
Listing plugins with pattern "rabbitmq_lvc_exchange" ...
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status: [failed to contact rabbit@shostakovich - status not shown]
 |/
[E ] rabbitmq_lvc_exchange 3.8.0
```
