### ISSUE TITLE
Where is the Plugin for RabbitMQ 3.11?

### ISSUE THREAD

**Issue by awdm** [rabbitmq/rabbitmq-lvc-exchange#34]
The readme says that the latest release targets RabbitMQ version 3.11, but the actual latest release targets 3.10 and can not be enabled with version 3.11.

**Comment by michaelklishin** [comment]
It says so as of #33.

**Comment by michaelklishin** [comment]
[Right here](https://github.com/rabbitmq/rabbitmq-lvc-exchange/releases/tag/v3.11.4).
