### ISSUE TITLE
Send last value to a new client if username is the same 

### ISSUE THREAD

**Issue by marhyno** [rabbitmq/rabbitmq-lvc-exchange#45]
### Is your feature request related to a problem? Please describe.

We found that, if you connect to the RabbitMQ using same SSL certificate which has the same username from different clients, the second client never receives the last value cached. E.g. I connect one app where username is PartnerClient and then I connect a different app which also has username PartnerClient. The second app never receives the last value cached because the plugin assumes it has already sent the message to that client.

### Describe the solution you'd like

I would like to receive the value when I connect with the same SSL certificate from a multiple apps (sources) to RabbitMQ

**Comment by gomoripeti** [comment]
hi @marhyno, what protocol do you use, maybe MQTT?

The lvc is an exchange which does not know about usernames or client ids. Additionally connections don't receive messages directly from exchanges. When a queue is bound to an lvc-exchange with a given routing key, the lvc-exchange will send the queue the last value that was published with the same routing key. The clients can connect to the broker and consume from that queue.

If you would like every connection to receive the last value published with the routing key "PartnerClient", then every AMQP connection needs to declare its own new (exclusive) queue and create a new binding with routing key "PartnerClient" to the lvc-exchange.

Could you clarify your topology within RabbitMQ? I might have misunderstood something.

**Comment by marhyno** [comment]
Thank @gomoripeti that makes perfect sense, you can close this issue, sorry for bothering.

**Comment by gomoripeti** [comment]
happy I could help

(I'm not an owner of this repo, just a community member so I cannot close this issue, but you as the reporter probably can)
