### ISSUE TITLE
Add support for e2e binding

### ISSUE THREAD

**Issue by santif** [rabbitmq/rabbitmq-lvc-exchange#9]
I'd like to declare e2e bindings from x-lvc exchanges

**Comment by santif** [comment]
I changed add_binding() implementation... eunit tests are pending!

https://github.com/santif/rabbitmq-lvc-plugin/commit/f4ea2c6194ad646ccacca05d7978bf9aad77a83c

**Comment by santif** [comment]
I added a testcase, but it fails... I checked the testcase and I think it is correct, and for some reason the message isn't routed to destination after binding (when binding and then publishing msg, works ok). It would be great if someone else can take a look to my implementation

https://github.com/santif/rabbitmq-lvc-plugin/commit/9e4124afc5870a50c0714d799c8cc00ea7a36694

Thanks!

**Comment by danielsnider** [comment]
I would really like this solved!
